# Generated by Django 4.2 on 2026-04-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'compliance_business_profiles',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='compliance.businessprofile')),
            ],
            options={
                'db_table': 'compliance_representatives',
            },
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=50)),
                ('file_key_encrypted', models.TextField()),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.businessprofile')),
            ],
            options={
                'db_table': 'compliance_kyc_documents',
            },
        ),
    ]
