# Generated by Django 4.2 on 2026-04-17 04:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('actor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('geo_city', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_country', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(default='success', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-ts'],
            },
        ),
    ]
