# Generated by Django 4.2 on 2026-04-17 04:53

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(default=links.models.generate_link_slug, max_length=10, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'payment_links',
                'ordering': ['-created_at'],
            },
        ),
    ]
