# Generated by Django 4.2 on 2026-04-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processor_settlement_id', models.CharField(db_index=True, max_length=255)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
