from rest_framework import serializers
from .models import Webhook, WebhookDelivery

class WebhookSerializer(serializers.ModelSerializer):
    class Meta:
        model = Webhook
        fields = [
            'id', 'url', 'events', 'secret', 
            'is_active', 'mode', 'created_at'
        ]
        read_only_fields = ['id', 'secret', 'created_at']

    def create(self, validated_data):
        # Secret is auto-generated by model default lambda
        return super().create(validated_data)

class WebhookDeliverySerializer(serializers.ModelSerializer):
    class Meta:
        model = WebhookDelivery
        fields = [
            'id', 'event_type', 'status', 
            'status_code', 'attempt_count', 'last_attempt_at'
        ]
