# Generated by Django 4.2 on 2026-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCharge',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_fiat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency_fiat', models.CharField(default='USD', max_length=3)),
                ('amount_crypto', models.DecimalField(decimal_places=18, max_digits=36)),
                ('currency_crypto', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('confirmations_required', models.IntegerField(default=2)),
                ('confirmations_received', models.IntegerField(default=0)),
                ('processor_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hosted_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'crypto_charges',
                'ordering': ['-created_at'],
            },
        ),
    ]
